services:
  backend:
    container_name: kpd-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: kpd-backend-docker
    restart: always
    env_file: 
      - .env
    ports:
      - 4000:3000
    networks:
      - internal

  frontend:
    container_name: kpd-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kpd-frontend-docker
    restart: always
    ports:
      - 8081:80
    networks:
      - external

  database:
    container_name: postgres-container
    image: postgres:alpine
    env_file: .env
    restart: always
    networks:
      - internal
    volumes:
      - database_volume:/data/database_volume

volumes:
  database_volume:

networks:
  internal:
  external:
